name: Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.4.2"]
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: View poetry --help
        run: poetry --help

      - name: Install dependencies
        run: poetry install

      - name: install pyinstaller
        run: poetry run pip install -U pyinstaller
      - name: Build execution file
        run: poetry run pyinstaller main.py --onefile

      - name: Sign the macos-version build
        if: ${{ matrix.os  == 'macos-latest' }}
        run: codesign --force -s - ./dist/main

      - name: Rename built binary
        run: poetry run mv ./dist/main ./dist/feedback-data-converter-${{ matrix.os }}

      - name: Store built binary
        uses: actions/upload-artifact@v3
        with:
          name: converter-binary
          path: dist
          retention-days: 5

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download built binary
        uses: actions/download-artifact@v3
        with:
          name: converter-binary
          path: ./dist/
      - name: Set env for release
        run: echo "DATE=$(date +'%Y-%m-%d %H:%M')" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/*
          name: ${{ env.DATE }}
          tag_name: ${{ env.DATE }}

    permissions:
      contents: write
